language: php

php:
  - '7.3'
  - '7.4'

branches:
  only:
    - master

before_script:
  - travis_retry composer self-update
  - travis_retry composer update --no-interaction --no-suggest

script:
  - vendor/bin/phpcs
  - vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)

cache:
  directories:
    - $HOME/.composer/cache